
input:
    sources:
      - type: 'Csv'
        csv_path: 'C:/Users/a.camarero.sierra/Downloads/events.csv'
        name: 'events'
        label: 'events'
        delimiter: ','

transformations:
    - type: "Select"
      cols: ['timestamp', 'event']


output:
  -   type: 'Csv'
      name: "test"
      path: "C:/Users/a.camarero.sierra/Downloads/Output"
      transformations:
        - type: "SortBy"
          column: "timestamp"